main:	obj/main.o obj/Doubly_Linked_List.o
	gcc -o main obj/main.o obj/Doubly_Linked_List.o

obj/main.o:	main.c
	gcc -o obj/main.o -c main.c

obj/singly_linked_list.o:	src/Doubly_Linked_List.c
	gcc -o obj/Doubly_Linked_List.o -c src/Doubly_Linked_List.c