test:	obj/test.o obj/singly_linked_list.o
	gcc -o test obj/test.o obj/singly_linked_list.o

obj/test.o:	test.c
	gcc -o obj/test.o -c test.c

obj/singly_linked_list.o:	src/singly_linked_list.c
	gcc -o obj/singly_linked_list.o -c src/singly_linked_list.c