test:	obj/test.o obj/array_list.o
	gcc -o test obj/test.o obj/array_list.o

obj/test.o:	test.c
	gcc -o obj/test.o -c test.c

obj/array_list.o:	src/array_list.c
	gcc -o obj/array_list.o -c src/array_list.c