#!/usr/bin/env python3

import sys
sys.path.append("../..")

import matplotlib.pyplot as plt
import pandas as pd
import sys
import math as m
from modules import pycla

def error(msg):
		print("ERROR: "+msg+"\n\nUSAGE:\n$ "+sys.argv[0]+" <options>\n\nOPTIONS:")
		print("-i <file-name>\t: Input File (.csv).")
		print("-ig <num>\t: Ignore first num rows of data.")
		print("-o <file-name>\t: Output File (.png OR .pdf)")

#READ CSV FILE
df = pd.read_csv(pycla.get_arg("i"))
df.hist()


#print(df)

outFile = pycla.get_arg("o")
if outFile == None:
	plt.show()             #plt.show() is required for displaying the histogram generated by df
else:
	plt.savefig(outFile, bbox_inches="tight")
	print("Plot saved to "+outFile) 
