#!/usr/bin/env python3

import sys
sys.path.append("../..")

import matplotlib.pyplot as plt
import pandas as pd

from modules import pycla

def error(msg):
		print("ERROR: "+msg+"\n\nUSAGE:\n$ "+sys.argv[0]+" <options>\n\nOPTIONS:")
		print("-i <file-name>\t: Input File (.csv).")
		print("-o <file-name>\t: Output File (.png OR .pdf)")

inFile = pycla.get_arg("i")
if inFile == None:
	print("No such dataset found!")
	exit()

#READ CSV FILE
df = pd.read_csv(inFile)
df.hist()

outFile = pycla.get_arg("o")
if outFile == None:
	plt.show()             #plt.show() is required for displaying the histogram generated by df
else:
	plt.savefig(outFile, bbox_inches="tight")
	print("Plot saved to " + outFile) 
